### ISSUE TITLE
add support for FluConsole package

### ISSUE THREAD

**Issue by yousefak007** [yelmuratoff/ispect#3]
FluConsole: Let Flutter print logs to display on the phone
Link: [FluConsole](https://pub.dev/packages/flu_console)

and also thanks for your work, it's a great library.

**Comment by yelmuratoff** [comment]
Hi! Thanks for the suggestion, I probably won't integrate the library, but
I will consider Flutter print logging. I'll look into this feature this
weekend. Thanks!
Regards, Yelaman.

пт, 26 июл. 2024 г. в 01:07, Yousef Alkhamesi ***@***.***>:

**Comment by yousefak007** [comment]
thank you, I also made the same request in the talker package [Frezyx/talker/issues/251](https://github.com/Frezyx/talker/issues/251)

**Comment by yelmuratoff** [comment]
@yousefak007 

I added this feature, it will appear on the next version 1.6.3. If there are any questions or errors, you can unsubscribe here or email me.
yelmuratovyelaman@gmail.com

<img width="293" alt="Снимок экрана 2024-07-26 в 01 58 51" src="https://github.com/user-attachments/assets/e535745e-9c8b-41f2-8287-5399e59b163f">

**Comment by yelmuratoff** [comment]
https://github.com/yelmuratoff/ispect/pull/4

**Comment by yelmuratoff** [comment]
@yousefak007 
I pushed it to pub dev with 1.6.3 version, please check example from GitHub for better understanding how add print handler to your project

**Comment by yousefak007** [comment]
thanks
