### ISSUE TITLE
No copyright included for the `inspector` package

### ISSUE THREAD

**Issue by kekland** [yelmuratoff/ispect#6]
Hi!

Noticed that this package is using a copy of `inspector` - however, I couldn't find the original copyright notice in the repository nor in the source code. To comply with the MIT license, any copies or portions of `inspector` must include the original copyright notice (https://github.com/kekland/inspector/blob/master/LICENSE) in the source code.

**Comment by yelmuratoff** [comment]
Hi, I originally added just your package, but it's not customizable, so I added it manually, but specified your package in the README and in the package descriptions.

You can see it here: `A package combining Inspector, Talker, and more from pub.dev for efficient project implementation`.
(Inside README.md file)

I can provide any authoring references you want, just let me know.
@kekland

**Comment by kekland** [comment]
Thanks for a quick reply!

Yes, I've seen the package being mentioned in README, however, the MIT license states that any copy of the source shall also include the license and the permission notice whenever it's used.

I'll open a PR which adds the appropriate license file to the `inspector` folder.

**Comment by yelmuratoff** [comment]
Good, I'll be only glad) Maybe in the future I'll throw a couple of PRs into your wonderful package too, I wish it lent itself more to visual customization, but I don't have time yet. Thank you!

**Comment by yelmuratoff** [comment]
@kekland I added it, thanks again! I apologize for missing the license, I honestly forgot about it.

**Comment by kekland** [comment]
no worries, all good :) glad that you found `inspector` useful
